version: '3'
services:
  db1:
    image: 'postgres:alpine'
    ports:
      - 5433:5432
    environment:

      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jobmanagement
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    command: [ "postgres", "-c", "log_statement=all" ]
volumes:
  pgdata: