version: '3'  # Docker Compose version

services:
  db1:  # PostgreSQL service
    image: 'postgres:alpine'
    restart: always  # Tự động khởi động lại nếu container bị dừng
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobmanagement
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:  # RabbitMQ service
    image: 'rabbitmq:3.6-management-alpine'  # Image with management UI
    restart: always
    ports:
      - '5672:5672' # AMQP port
      - '15672:15672'  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
