spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jobmanagement
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  spring:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
